package com.keendo.biz.model;

/**
 * 全局配置Item
 * @author hebo2
 *
 */
public class GlobalConfig {

    private String key;
    private String value;
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cons_global_config.key
     *
     * @return the value of cons_global_config.key
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cons_global_config.key
     *
     * @param key the value for cons_global_config.key
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cons_global_config.value
     *
     * @return the value of cons_global_config.value
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cons_global_config.value
     *
     * @param value the value for cons_global_config.value
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}
    
    
}